export const Headphones = [
  {
    id: 1,
    name: "Sony Pro Headphones",
    category: "headphones",
    price: 231.48,
    currency: "USD",
    description:
      "Sony premium headphones with top-tier features and performance.",
    brand: "Sony",
    rating: 4.8,
    reviews: 6027,
    color: "White",
    image:
      "https://m.media-amazon.com/images/I/21F6MKKV6EL._SX300_SY300_QL70_FMwebp_.jpg",
    stock: 74,
    discount: 3,
    features: [
      "Fast charging",
      "Wireless",
      "Bluetooth 5.0",
      "Voice assistant support",
    ],
  },
  {
    id: 2,
    name: "Bose QuietComfort 45",
    category: "headphones",
    price: 299.99,
    currency: "USD",
    description:
      "Noise-cancelling headphones with long battery life and balanced audio.",
    brand: "Bose",
    rating: 4.7,
    reviews: 3821,
    color: "Black",
    image: "https://m.media-amazon.com/images/I/51HHABMPoVL._SX522_.jpg",
    stock: 52,
    discount: 5,
    features: [
      "Noise cancellation",
      "Wired + Wireless",
      "Comfort fit",
      "30-hour battery",
    ],
  },
  {
    id: 3,
    name: "JBL Tune 760NC",
    category: "headphones",
    price: 129.0,
    currency: "USD",
    description:
      "Bass-heavy wireless headphones with active noise cancellation.",
    brand: "JBL",
    rating: 4.3,
    reviews: 1945,
    color: "Blue",
    image:
      "https://m.media-amazon.com/images/I/31K0TGXVovL._SX300_SY300_QL70_FMwebp_.jpg",
    stock: 90,
    discount: 10,
    features: ["ANC", "Bluetooth 5.0", "Foldable design", "Voice assistant"],
  },
  {
    id: 4,
    name: "Sennheiser HD 450BT",
    category: "headphones",
    price: 179.95,
    currency: "USD",
    description:
      "High-quality sound and noise cancellation with 30-hour battery life.",
    brand: "Sennheiser",
    rating: 4.5,
    reviews: 2104,
    color: "Black",
    image:
      "https://m.media-amazon.com/images/I/31KL6Rv4HhL._SX300_SY300_QL70_FMwebp_.jpg",
    stock: 43,
    discount: 7,
    features: [
      "Bluetooth 5.0",
      "Active Noise Cancellation",
      "30-hour battery",
      "USB-C",
    ],
  },
  {
    id: 5,
    name: "Beats Studio3",
    category: "headphones",
    price: 349.95,
    currency: "USD",
    description:
      "Premium headphones with adaptive noise cancelling and Apple W1 chip.",
    brand: "Beats",
    rating: 4.6,
    reviews: 4875,
    color: "Red",
    image: "https://m.media-amazon.com/images/I/618aVzbPMjL._SX679_.jpg",
    stock: 28,
    discount: 6,
    features: ["W1 chip", "ANC", "Fast Fuel", "On-ear controls"],
  },
  // {
  //   id: 6,
  //   name: "Skullcandy Crusher Evo",
  //   category: "headphones",
  //   price: 199.99,
  //   currency: "USD",
  //   description:
  //     "Adjustable sensory bass and personalized sound with long battery life.",
  //   brand: "Skullcandy",
  //   rating: 4.4,
  //   reviews: 3210,
  //   color: "Gray",
  //   image: "https://example.com/images/headphones-6.jpg",
  //   stock: 66,
  //   discount: 8,
  //   features: [
  //     "Sensory bass",
  //     "Personal Sound",
  //     "40-hour battery",
  //     "Tile Tracker",
  //   ],
  // },
];

export const Mobiles = [
  {
    id: 7,
    name: "iPhone 14 Pro Max",
    category: "mobile",
    price: 1199.99,
    currency: "USD",
    description: "Apple's flagship phone with A16 chip and dynamic island.",
    brand: "Apple",
    rating: 4.9,
    reviews: 9810,
    color: "Deep Purple",
    image:
      "https://m.media-amazon.com/images/I/61giwQtR1qL._AC_UY327_FMwebp_QL65_.jpg",
    stock: 34,
    discount: 4,
    features: ["A16 Bionic", "48MP Camera", "Always-On Display", "Face ID"],
  },
  {
    id: 8,
    name: "Samsung Galaxy S23 Ultra",
    category: "mobile",
    price: 1099.99,
    currency: "USD",
    description:
      "Top-tier Samsung phone with 200MP camera and Snapdragon 8 Gen 2.",
    brand: "Samsung",
    rating: 4.8,
    reviews: 8425,
    color: "Phantom Black",
    image: "https://m.media-amazon.com/images/I/71goZuIha-L._SX679_.jpg",
    stock: 39,
    discount: 6,
    features: ["200MP Camera", "S Pen", "8K Video", "120Hz AMOLED"],
  },
  {
    id: 9,
    name: "Google Pixel 7 Pro",
    category: "mobile",
    price: 899.0,
    currency: "USD",
    description:
      "Clean Android experience with great camera and Tensor G2 chip.",
    brand: "Google",
    rating: 4.7,
    reviews: 5250,
    color: "Obsidian",
    image:
      "https://m.media-amazon.com/images/I/31hSeN8NeZL._SX300_SY300_QL70_FMwebp_.jpg",
    stock: 42,
    discount: 5,
    features: ["Tensor G2", "Super Res Zoom", "Magic Eraser", "5G"],
  },
  {
    id: 10,
    name: "OnePlus 11 5G",
    category: "mobile",
    price: 729.99,
    currency: "USD",
    description:
      "High performance and fast charging flagship at a great price.",
    brand: "OnePlus",
    rating: 4.5,
    reviews: 3120,
    color: "Titan Black",
    image: "https://m.media-amazon.com/images/I/414+xRBltFL._SY300_SX300_.jpg",
    stock: 54,
    discount: 7,
    features: [
      "Snapdragon 8 Gen 2",
      "120Hz",
      "100W Fast Charging",
      "Hasselblad Camera",
    ],
  },
  {
    id: 11,
    name: "Xiaomi 13 Pro",
    category: "mobile",
    price: 799.0,
    currency: "USD",
    description: "Premium Xiaomi phone with Leica lens and top specs.",
    brand: "Xiaomi",
    rating: 4.4,
    reviews: 2890,
    color: "Ceramic White",
    image: "https://m.media-amazon.com/images/I/41eB+jXzGsL._SY300_SX300_.jpg",
    stock: 61,
    discount: 10,
    features: [
      "Leica Camera",
      "Snapdragon 8 Gen 2",
      "120W Charging",
      "WQHD+ Display",
    ],
  },
  // {
  //   id: 12,
  //   name: "Realme GT Neo 5",
  //   category: "mobile",
  //   price: 549.0,
  //   currency: "USD",
  //   description: "Blazing fast charging with good performance at a lower cost.",
  //   brand: "Realme",
  //   rating: 4.3,
  //   reviews: 1582,
  //   color: "Pulse Purple",
  //   image: "https://example.com/images/realme-gt-neo5.jpg",
  //   stock: 70,
  //   discount: 9,
  //   features: [
  //     "240W Charging",
  //     "RGB light",
  //     "Snapdragon 8+ Gen 1",
  //     "144Hz Display",
  //   ],
  // },
];
